{
    "name": "Les Rapports  de paie",
    "version": "1.0",
    "depends": ['base','hr',"hr_payroll_ci", 'report_xlsx'],
    "author": "SIIG",
    "category": "hr",
    "description": """
    This module provide :
    """,
    'data': [
        "data/report_paperformat.xml",
        'data/sequence_disa.xml',
        'data/sequence_cnps_mensuel.xml',
        'data/sequence_cnps_trimestriel.xml',
        'data/sequence_dasc.xml',
        #'data/report_templates.xml',
        'wizard/HrPayrollView.xml',
        'wizard/hr_its_view.xml',
        'wizard/HrCnpsTrimestrielView.xml',
        'wizard/hrPayrollDISAView.xml',
        'wizard/hrPayrollFDFPView.xml',
        "raports/payroll_raport.xml",
        "raports/report_fdfp.xml",
        "raports/report_hr_its.xml",
        'views/HrSalaryRuleView.xml',
        'views/report_cnps_trimestriel.xml',
        'views/report_cnps_monthly.xml',
        'views/report_dasc.xml',
        'views/report_hr_disa.xml',
        'views/report_payroll.xml',
    ],
    'demo_xml': [],
    'installable': True,
    'active': False,
#    'certificate': 'certificate',
}